# Generated by Django 4.2.23 on 2025-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crewaiplatform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodel",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic (Claude)"),
                    ("azure_openai", "Azure OpenAI"),
                    ("ollama", "Ollama (本地)"),
                    ("huggingface", "HuggingFace"),
                    ("google", "Google (PaLM/Gemini)"),
                    ("cohere", "Cohere"),
                    ("moonshot", "Moonshot"),
                    ("custom", "自定义"),
                ],
                help_text="LangChain支持的模型提供商",
                max_length=32,
                verbose_name="提供商",
            ),
        ),
    ]
