# Generated by Django 4.2.23 on 2025-08-02 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crewaiplatform", "0002_add_crewai_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="用于程序识别的唯一代码，如：llm_provider",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="字典代码只能包含小写字母、数字和下划线，且必须以字母开头",
                                regex="^[a-z][a-z0-9_]*$",
                            )
                        ],
                        verbose_name="字典代码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="字典的显示名称，如：LLM供应商",
                        max_length=100,
                        verbose_name="字典名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="字典用途和说明",
                        null=True,
                        verbose_name="字典描述",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否启用此字典类型",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="数字越小排序越靠前",
                        verbose_name="排序顺序",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "字典类型",
                "verbose_name_plural": "字典类型",
                "db_table": "sys_dictionary",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DictionaryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="用于程序识别的代码，如：openai、gpt-4",
                        max_length=100,
                        verbose_name="字典项代码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="显示给用户的名称，如：OpenAI、GPT-4",
                        max_length=100,
                        verbose_name="字典项名称",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="额外的配置信息，如API端点等",
                        null=True,
                        verbose_name="字典项值",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="详细说明信息",
                        null=True,
                        verbose_name="字典项描述",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否启用此字典项",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="数字越小排序越靠前",
                        verbose_name="排序顺序",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        help_text="此项目所属的字典类型",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crewaiplatform.dictionary",
                        verbose_name="所属字典",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="用于建立二级关系，如模型隶属于供应商",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="crewaiplatform.dictionaryitem",
                        verbose_name="父级字典项",
                    ),
                ),
            ],
            options={
                "verbose_name": "字典项",
                "verbose_name_plural": "字典项",
                "db_table": "sys_dictionary_item",
                "ordering": ["sort_order", "created_at"],
                "unique_together": {("dictionary", "code")},
            },
        ),
    ]
