# Generated by Django 4.2.23 on 2025-08-07 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crewaiplatform", "0002_alter_llmmodel_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="新会话",
                        help_text="用户可自定义的会话标题",
                        max_length=255,
                        verbose_name="会话标题",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="会话的详细描述信息",
                        null=True,
                        verbose_name="会话描述",
                    ),
                ),
                (
                    "agent_selection_mode",
                    models.CharField(
                        choices=[
                            ("auto", "自动选择"),
                            ("manual", "手动选择"),
                            ("smart", "智能推荐"),
                        ],
                        default="manual",
                        help_text="Agent的选择方式",
                        max_length=32,
                        verbose_name="Agent选择模式",
                    ),
                ),
                (
                    "total_messages",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="会话中的总消息数量",
                        verbose_name="总消息数",
                    ),
                ),
                (
                    "total_agent_calls",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="会话中的总Agent调用次数",
                        verbose_name="总Agent调用数",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("archived", "已归档")],
                        default="active",
                        help_text="会话状态",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="会话的最后活动时间",
                        null=True,
                        verbose_name="最后活动时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "primary_agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="手动模式下的默认Agent",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_conversations",
                        to="crewaiplatform.crewaiagent",
                        verbose_name="主要Agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="会话所属用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天会话",
                "verbose_name_plural": "聊天会话",
                "db_table": "chat_conversation",
                "ordering": ["-last_activity_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("assistant", "助手"),
                            ("system", "系统"),
                        ],
                        help_text="消息发送者的角色",
                        max_length=32,
                        verbose_name="消息角色",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="消息的文本内容", verbose_name="消息内容"
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        blank=True,
                        help_text="Agent的显示名称",
                        max_length=128,
                        null=True,
                        verbose_name="Agent名称",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("sent", "已发送"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="sent",
                        help_text="消息的处理状态",
                        max_length=32,
                        verbose_name="消息状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="消息处理失败时的错误详情",
                        null=True,
                        verbose_name="错误信息",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="处理消息的Agent",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="crewaiplatform.crewaiagent",
                        verbose_name="响应Agent",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="消息所属的聊天会话",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="crewaiplatform.chatconversation",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天消息",
                "verbose_name_plural": "聊天消息",
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatAgentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_description",
                    models.TextField(
                        help_text="Agent需要执行的任务描述", verbose_name="任务描述"
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        help_text="Agent的显示名称",
                        max_length=128,
                        verbose_name="Agent名称",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "执行失败"),
                        ],
                        default="pending",
                        help_text="任务的执行状态",
                        max_length=32,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="任务开始执行的时间",
                        null=True,
                        verbose_name="开始时间",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="任务执行结束的时间",
                        null=True,
                        verbose_name="结束时间",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="任务执行耗时，单位：毫秒",
                        verbose_name="执行时间(毫秒)",
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="Agent任务的执行结果",
                        null=True,
                        verbose_name="执行结果",
                    ),
                ),
                (
                    "error_details",
                    models.TextField(
                        blank=True,
                        help_text="任务执行失败时的详细错误信息",
                        null=True,
                        verbose_name="错误详情",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="执行此任务的Agent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_tasks",
                        to="crewaiplatform.crewaiagent",
                        verbose_name="执行Agent",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="任务所属的聊天会话",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tasks",
                        to="crewaiplatform.chatconversation",
                        verbose_name="所属会话",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="任务关联的消息",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tasks",
                        to="crewaiplatform.chatmessage",
                        verbose_name="关联消息",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent任务",
                "verbose_name_plural": "Agent任务",
                "db_table": "chat_agent_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_3154fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["role"], name="chat_messag_role_9cd150_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["status"], name="chat_messag_status_8c4650_idx"),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["user", "status"], name="chat_conver_user_id_f98e31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["last_activity_at"], name="chat_conver_last_ac_535bed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["created_at"], name="chat_conver_created_656b50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatagenttask",
            index=models.Index(
                fields=["conversation", "status"], name="chat_agent__convers_74a335_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatagenttask",
            index=models.Index(
                fields=["agent", "status"], name="chat_agent__agent_i_630c67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatagenttask",
            index=models.Index(
                fields=["status", "created_at"], name="chat_agent__status_de8a2b_idx"
            ),
        ),
    ]